### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by urbany** [ember-cli-deploy/ember-cli-deploy-s3-index#60]
Hey,

Just tried installing ember-cli-deploy-s3-index  for the first time and i get the following error:

```
# ember install ember-cli-deploy-s3-index 
Cannot find module 'lodash'
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/code/project/node_modules/ember-cli-deploy-display-revisions/index.js:7:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

is lodash a required dependency?

**Comment by lukemelia** [comment]
@urbany Looks like the error is coming from `ember-cli-deploy-display-revisions`, which does use lodash.

**Comment by lukemelia** [comment]
I'll close this and take a look on that repo.

**Comment by lukemelia** [comment]
Hoping that [this](https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions/pull/10) is going to fix it.

**Comment by lukemelia** [comment]
This should be fixed with ember-cli-deploy-display-revisions v0.2.1

**Comment by urbany** [comment]
Seems ok now, thank you so much for the fast response!
